name: ai4mi-pcam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip>=23.2.1
  - pytorch-cuda>=11.8
  - pytorch>=2.0.0
  - numpy
  - lightning
  - pip:
    - ruff
    - lightning[pytorch-extra]"
